project:
  type: website

website:
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Slides
      - href: problem-sets.qmd
        text: Problem Sets
    
metadata-files:
  - assets/quarto-course-website_files/sidebar-nav.yml
#  - sidebar-nav.yml

format:
  html:
    theme: [sandstone, assets/styles.scss]
    toc: true
