on:
  push:
    branches:
      - master
  
name: "Publish to GH pages"
jobs:
  publish:
    runs-on: ubuntu-20.04
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
    steps:
      # for accessing this repo's assets in the container
      - name: Check out the repo
        uses: actions/checkout@v3
      # run the container, attaching this repo as a working directory
      - name: Install quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install tinytex
        run: |
          quarto install tinytex
      - name: publish
        run: |
          # exit if any command returns non-zero exit
          # set -e

          # render partial site
          quarto run partial-render.ts
             
          # render for real
          # quarto render --profile partial-site

          git config --global user.email "scf@stat.berkeley.edu"
          git config --global user.name "GitHub Action"
          
          # publish rendered site to stat20.org
          quarto publish gh-pages --profile partial-render --no-render
